version: '3.8'

services:
  app-goles:
    build: .
    image: jenkinsiker:latest
    stdin_open: true
    tty: true
    networks:
      - jenkins-net

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8090:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
    networks:
      - jenkins-net

networks:
  jenkins-net:

volumes:
  jenkins_data:
